"""
Seed recipes for master@mise.com directly via MongoDB.
Run from the backend/ directory: python seed_master.py
"""
import asyncio
from datetime import datetime, timezone
from motor.motor_asyncio import AsyncIOMotorClient
from dotenv import load_dotenv
import os

load_dotenv()

URI = os.getenv("MONGODB_URI", "mongodb://localhost:27017")
DB  = os.getenv("DATABASE_NAME", "cookindb")

RECIPES = [
    # ── Italian ───────────────────────────────────────────────────────────────
    {
        "recipe_name": "Cacio e Pepe",
        "cuisine": "Italian",
        "category": "Pasta",
        "tags": "pasta, quick, vegetarian",
        "prep_time": 5,
        "cook_time": 20,
        "servings": 2,
        "image_url": "https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800",
        "ingredients": [
            {"name": "Spaghetti or tonnarelli", "quantity": "200", "unit": "g"},
            {"name": "Pecorino Romano", "quantity": "80", "unit": "g"},
            {"name": "Parmesan", "quantity": "40", "unit": "g"},
            {"name": "Black pepper (coarsely ground)", "quantity": "2", "unit": "tsp"},
            {"name": "Salt", "quantity": "1", "unit": "tbsp"},
        ],
        "instructions": "Cook pasta in well-salted boiling water until 2 minutes shy of al dente.\nToast black pepper in a dry skillet until fragrant, about 1 minute.\nFinely grate both cheeses and mix together.\nReserve 1 cup pasta water before draining.\nAdd a splash of pasta water to the pepper pan over low heat, add pasta and toss.\nRemove from heat, add cheese gradually while tossing vigorously, adding pasta water to form a creamy sauce.\nServe immediately with extra cheese and pepper.",
    },
    {
        "recipe_name": "Risotto al Limone",
        "cuisine": "Italian",
        "category": "Rice",
        "tags": "risotto, vegetarian, elegant",
        "prep_time": 10,
        "cook_time": 30,
        "servings": 4,
        "image_url": "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=800",
        "ingredients": [
            {"name": "Arborio rice", "quantity": "320", "unit": "g"},
            {"name": "Vegetable broth (warm)", "quantity": "1.2", "unit": "L"},
            {"name": "White wine", "quantity": "120", "unit": "ml"},
            {"name": "Shallots", "quantity": "2", "unit": ""},
            {"name": "Butter", "quantity": "60", "unit": "g"},
            {"name": "Parmesan", "quantity": "80", "unit": "g"},
            {"name": "Lemon (zest and juice)", "quantity": "2", "unit": ""},
            {"name": "Olive oil", "quantity": "2", "unit": "tbsp"},
        ],
        "instructions": "Heat broth and keep it warm on a back burner.\nSauté shallots in olive oil and 20g butter over medium heat until soft.\nAdd rice and toast 2 minutes, stirring constantly.\nPour in wine and stir until absorbed.\nAdd broth one ladle at a time, stirring constantly and waiting until each ladle is absorbed before adding the next.\nAfter 18–20 minutes the rice should be al dente.\nRemove from heat, stir in remaining butter, parmesan, lemon zest and juice.\nRest 1 minute, season to taste, serve.",
    },
    {
        "recipe_name": "Classic Lasagna",
        "cuisine": "Italian",
        "category": "Pasta",
        "tags": "pasta, comfort food, weekend",
        "prep_time": 30,
        "cook_time": 90,
        "servings": 8,
        "image_url": "https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=800",
        "ingredients": [
            {"name": "Lasagna sheets", "quantity": "300", "unit": "g"},
            {"name": "Ground beef", "quantity": "500", "unit": "g"},
            {"name": "Italian sausage", "quantity": "250", "unit": "g"},
            {"name": "Crushed tomatoes", "quantity": "800", "unit": "g"},
            {"name": "Whole milk", "quantity": "1", "unit": "L"},
            {"name": "Butter", "quantity": "60", "unit": "g"},
            {"name": "Flour", "quantity": "60", "unit": "g"},
            {"name": "Mozzarella", "quantity": "300", "unit": "g"},
            {"name": "Parmesan", "quantity": "100", "unit": "g"},
            {"name": "Onion", "quantity": "1", "unit": ""},
            {"name": "Garlic", "quantity": "4", "unit": "cloves"},
        ],
        "instructions": "Make béchamel: melt butter, whisk in flour, cook 2 min, add warm milk gradually, season with nutmeg, salt, pepper. Simmer until thick.\nBrown beef and sausage with onion and garlic. Add tomatoes, simmer 30 minutes. Season well.\nPreheat oven to 190°C. Grease a 9x13 baking dish.\nLayer: meat sauce, pasta sheets, béchamel, mozzarella. Repeat 3 times. Finish with béchamel and parmesan.\nCover with foil, bake 45 min. Uncover, bake 20 min until golden and bubbling.\nRest 20 minutes before cutting.",
    },
    # ── Mexican ───────────────────────────────────────────────────────────────
    {
        "recipe_name": "Birria Tacos",
        "cuisine": "Mexican",
        "category": "Tacos",
        "tags": "tacos, braised, weekend",
        "prep_time": 30,
        "cook_time": 180,
        "servings": 6,
        "image_url": "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800",
        "ingredients": [
            {"name": "Beef chuck", "quantity": "1.5", "unit": "kg"},
            {"name": "Guajillo chiles (dried)", "quantity": "6", "unit": ""},
            {"name": "Ancho chiles (dried)", "quantity": "3", "unit": ""},
            {"name": "Chipotle in adobo", "quantity": "2", "unit": ""},
            {"name": "Beef broth", "quantity": "1", "unit": "L"},
            {"name": "Garlic", "quantity": "6", "unit": "cloves"},
            {"name": "Onion", "quantity": "1", "unit": ""},
            {"name": "Corn tortillas", "quantity": "18", "unit": ""},
            {"name": "Oaxaca cheese", "quantity": "200", "unit": "g"},
            {"name": "White onion (diced)", "quantity": "1", "unit": ""},
            {"name": "Cilantro", "quantity": "1", "unit": "bunch"},
            {"name": "Lime", "quantity": "3", "unit": ""},
        ],
        "instructions": "Toast dried chiles in a dry skillet 30 seconds each side, then soak in hot water 20 minutes.\nBlend soaked chiles with garlic, onion, chipotle, and some soaking water until smooth.\nSeason beef generously with salt. Sear in a Dutch oven until browned on all sides.\nPour chile sauce and broth over beef. Bring to a simmer, cover and braise 2.5–3 hours until very tender.\nShred beef, reserve the consommé (braising liquid) for dipping.\nDip tortillas in consommé, fry on a hot skillet. Add cheese and beef, fold and cook until crispy.\nServe with dipping consommé, diced onion, cilantro, lime.",
    },
    {
        "recipe_name": "Guacamole",
        "cuisine": "Mexican",
        "category": "Dip",
        "tags": "dip, quick, vegan, healthy",
        "prep_time": 10,
        "cook_time": 0,
        "servings": 4,
        "image_url": "https://images.unsplash.com/photo-1620921571745-5e3e9f64ec48?w=800",
        "ingredients": [
            {"name": "Ripe avocados", "quantity": "3", "unit": ""},
            {"name": "Lime juice", "quantity": "2", "unit": "tbsp"},
            {"name": "Jalapeño", "quantity": "1", "unit": ""},
            {"name": "White onion", "quantity": "1/4", "unit": ""},
            {"name": "Cilantro", "quantity": "1/4", "unit": "cup"},
            {"name": "Garlic", "quantity": "1", "unit": "clove"},
            {"name": "Flaky salt", "quantity": "1", "unit": "tsp"},
        ],
        "instructions": "Finely dice jalapeño (remove seeds for less heat), onion, and cilantro. Mince garlic.\nHalve and pit avocados. Scoop flesh into a bowl.\nAdd lime juice and salt, mash to your preferred texture (chunky or smooth).\nFold in jalapeño, onion, garlic, and cilantro.\nTaste and adjust seasoning. Add more lime or salt as needed.\nPress plastic wrap directly onto surface to prevent browning if not serving immediately.",
    },
    {
        "recipe_name": "Shakshuka",
        "cuisine": "Mediterranean",
        "category": "Breakfast",
        "tags": "breakfast, eggs, vegetarian, one-pan",
        "prep_time": 10,
        "cook_time": 25,
        "servings": 4,
        "image_url": "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800",
        "ingredients": [
            {"name": "Eggs", "quantity": "6", "unit": ""},
            {"name": "Crushed tomatoes", "quantity": "800", "unit": "g"},
            {"name": "Red bell pepper", "quantity": "2", "unit": ""},
            {"name": "Onion", "quantity": "1", "unit": ""},
            {"name": "Garlic", "quantity": "4", "unit": "cloves"},
            {"name": "Cumin", "quantity": "1", "unit": "tsp"},
            {"name": "Paprika", "quantity": "1", "unit": "tsp"},
            {"name": "Cayenne pepper", "quantity": "1/4", "unit": "tsp"},
            {"name": "Feta cheese", "quantity": "100", "unit": "g"},
            {"name": "Fresh parsley", "quantity": "1/4", "unit": "cup"},
            {"name": "Olive oil", "quantity": "3", "unit": "tbsp"},
        ],
        "instructions": "Heat olive oil in a wide skillet over medium heat. Sauté onion and bell pepper until soft, 8 minutes.\nAdd garlic, cumin, paprika, and cayenne. Cook 1 minute until fragrant.\nPour in crushed tomatoes, season with salt and pepper. Simmer 10 minutes until slightly thickened.\nMake 6 wells in the sauce. Crack an egg into each well.\nCover and cook 5–8 minutes depending on preferred yolk doneness.\nCrumble feta on top, garnish with parsley. Serve with crusty bread.",
    },
    # ── Asian ─────────────────────────────────────────────────────────────────
    {
        "recipe_name": "Pad Thai",
        "cuisine": "Thai",
        "category": "Noodles",
        "tags": "noodles, quick, weeknight",
        "prep_time": 20,
        "cook_time": 15,
        "servings": 2,
        "image_url": "https://images.unsplash.com/photo-1559314809-0d155014e29e?w=800",
        "ingredients": [
            {"name": "Rice noodles (flat)", "quantity": "200", "unit": "g"},
            {"name": "Shrimp or chicken", "quantity": "250", "unit": "g"},
            {"name": "Eggs", "quantity": "2", "unit": ""},
            {"name": "Bean sprouts", "quantity": "1", "unit": "cup"},
            {"name": "Green onions", "quantity": "3", "unit": ""},
            {"name": "Fish sauce", "quantity": "3", "unit": "tbsp"},
            {"name": "Tamarind paste", "quantity": "2", "unit": "tbsp"},
            {"name": "Brown sugar", "quantity": "1", "unit": "tbsp"},
            {"name": "Oyster sauce", "quantity": "1", "unit": "tbsp"},
            {"name": "Peanuts (crushed)", "quantity": "1/4", "unit": "cup"},
            {"name": "Lime", "quantity": "2", "unit": ""},
            {"name": "Vegetable oil", "quantity": "3", "unit": "tbsp"},
        ],
        "instructions": "Soak noodles in warm water 30 minutes until pliable but still firm. Drain.\nMix fish sauce, tamarind, brown sugar, and oyster sauce in a small bowl.\nHeat wok over high heat until smoking. Add oil and cook protein until done, set aside.\nPush to the side, scramble eggs.\nAdd noodles and sauce, toss constantly 2–3 minutes.\nAdd protein, bean sprouts, and green onions. Toss 1 more minute.\nServe topped with peanuts, lime wedges, and extra fish sauce on the side.",
    },
    {
        "recipe_name": "Chicken Teriyaki",
        "cuisine": "Japanese",
        "category": "Main",
        "tags": "chicken, quick, weeknight",
        "prep_time": 10,
        "cook_time": 20,
        "servings": 4,
        "image_url": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800",
        "ingredients": [
            {"name": "Chicken thighs (boneless)", "quantity": "700", "unit": "g"},
            {"name": "Soy sauce", "quantity": "60", "unit": "ml"},
            {"name": "Mirin", "quantity": "60", "unit": "ml"},
            {"name": "Sake", "quantity": "60", "unit": "ml"},
            {"name": "Sugar", "quantity": "2", "unit": "tbsp"},
            {"name": "Sesame oil", "quantity": "1", "unit": "tsp"},
            {"name": "Green onions", "quantity": "3", "unit": ""},
            {"name": "Sesame seeds", "quantity": "1", "unit": "tbsp"},
        ],
        "instructions": "Combine soy sauce, mirin, sake, and sugar in a saucepan. Simmer until slightly thickened, about 5 minutes.\nScore chicken thighs and season with salt and pepper.\nHeat sesame oil in a skillet over medium-high. Place chicken skin-side down, cook 7 minutes.\nFlip and cook 5 more minutes. Brush with teriyaki sauce repeatedly.\nSlice and serve over rice, drizzle remaining sauce on top.\nGarnish with green onions and sesame seeds.",
    },
    {
        "recipe_name": "Gyoza",
        "cuisine": "Japanese",
        "category": "Appetizer",
        "tags": "dumplings, weekend, appetizer",
        "prep_time": 45,
        "cook_time": 15,
        "servings": 4,
        "image_url": "https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=800",
        "ingredients": [
            {"name": "Gyoza wrappers", "quantity": "40", "unit": ""},
            {"name": "Ground pork", "quantity": "300", "unit": "g"},
            {"name": "Napa cabbage", "quantity": "200", "unit": "g"},
            {"name": "Garlic", "quantity": "3", "unit": "cloves"},
            {"name": "Ginger", "quantity": "1", "unit": "tbsp"},
            {"name": "Soy sauce", "quantity": "2", "unit": "tbsp"},
            {"name": "Sesame oil", "quantity": "1", "unit": "tbsp"},
            {"name": "Rice vinegar", "quantity": "3", "unit": "tbsp"},
            {"name": "Chili oil", "quantity": "1", "unit": "tsp"},
        ],
        "instructions": "Finely chop cabbage, salt it, let sit 10 minutes, then squeeze out moisture.\nMix pork, cabbage, garlic, ginger, 1 tbsp soy sauce, and sesame oil.\nPlace 1 tsp filling in center of each wrapper. Moisten edge with water, fold and pleat to seal.\nHeat oil in a non-stick skillet over medium-high. Add gyoza flat-side down, cook 2 minutes until golden.\nAdd 1/3 cup water, cover immediately, steam 5 minutes.\nRemove lid, cook until water evaporates and bottoms are crispy.\nMix remaining soy sauce with rice vinegar and chili oil for dipping.",
    },
    {
        "recipe_name": "Bibimbap",
        "cuisine": "Korean",
        "category": "Rice",
        "tags": "healthy, vegetarian, colorful",
        "prep_time": 30,
        "cook_time": 20,
        "servings": 4,
        "image_url": "https://images.unsplash.com/photo-1553163147-622ab57be1c7?w=800",
        "ingredients": [
            {"name": "Cooked short-grain rice", "quantity": "4", "unit": "cups"},
            {"name": "Spinach", "quantity": "200", "unit": "g"},
            {"name": "Bean sprouts", "quantity": "200", "unit": "g"},
            {"name": "Carrots", "quantity": "2", "unit": ""},
            {"name": "Zucchini", "quantity": "1", "unit": ""},
            {"name": "Shiitake mushrooms", "quantity": "150", "unit": "g"},
            {"name": "Eggs", "quantity": "4", "unit": ""},
            {"name": "Gochujang", "quantity": "4", "unit": "tbsp"},
            {"name": "Sesame oil", "quantity": "2", "unit": "tbsp"},
            {"name": "Soy sauce", "quantity": "1", "unit": "tbsp"},
            {"name": "Garlic", "quantity": "3", "unit": "cloves"},
        ],
        "instructions": "Blanch spinach and bean sprouts separately, squeeze dry, season with sesame oil, soy sauce, and garlic.\nSauté julienned carrots, zucchini, and mushrooms separately with sesame oil and salt.\nFry eggs sunny-side up or to your liking.\nDivide rice between warm bowls.\nArrange each vegetable in sections around the bowl.\nPlace egg on top, add a spoonful of gochujang.\nDrizzle with sesame oil. Mix vigorously before eating.",
    },
    {
        "recipe_name": "Thai Green Curry",
        "cuisine": "Thai",
        "category": "Curry",
        "tags": "curry, coconut, weeknight",
        "prep_time": 15,
        "cook_time": 25,
        "servings": 4,
        "image_url": "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800",
        "ingredients": [
            {"name": "Chicken breast", "quantity": "600", "unit": "g"},
            {"name": "Coconut milk", "quantity": "400", "unit": "ml"},
            {"name": "Green curry paste", "quantity": "3", "unit": "tbsp"},
            {"name": "Fish sauce", "quantity": "2", "unit": "tbsp"},
            {"name": "Palm sugar", "quantity": "1", "unit": "tbsp"},
            {"name": "Thai eggplant", "quantity": "200", "unit": "g"},
            {"name": "Bamboo shoots", "quantity": "1", "unit": "cup"},
            {"name": "Kaffir lime leaves", "quantity": "4", "unit": ""},
            {"name": "Thai basil", "quantity": "1", "unit": "cup"},
            {"name": "Vegetable oil", "quantity": "2", "unit": "tbsp"},
        ],
        "instructions": "Heat oil in a wok over medium-high. Fry curry paste 1–2 minutes until fragrant.\nPour in coconut milk, stir to combine.\nAdd chicken, eggplant, bamboo shoots, and kaffir lime leaves.\nSimmer 15 minutes until chicken is cooked through and eggplant is tender.\nSeason with fish sauce and palm sugar, taste and adjust.\nRemove from heat, stir in Thai basil.\nServe over jasmine rice.",
    },
    # ── American ──────────────────────────────────────────────────────────────
    {
        "recipe_name": "Mac and Cheese",
        "cuisine": "American",
        "category": "Pasta",
        "tags": "comfort food, quick, vegetarian",
        "prep_time": 10,
        "cook_time": 20,
        "servings": 4,
        "image_url": "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=800",
        "ingredients": [
            {"name": "Elbow macaroni", "quantity": "400", "unit": "g"},
            {"name": "Sharp cheddar", "quantity": "300", "unit": "g"},
            {"name": "Gruyère", "quantity": "100", "unit": "g"},
            {"name": "Whole milk", "quantity": "500", "unit": "ml"},
            {"name": "Butter", "quantity": "40", "unit": "g"},
            {"name": "Flour", "quantity": "40", "unit": "g"},
            {"name": "Dijon mustard", "quantity": "1", "unit": "tsp"},
            {"name": "Paprika", "quantity": "1/2", "unit": "tsp"},
            {"name": "Panko breadcrumbs", "quantity": "1/2", "unit": "cup"},
        ],
        "instructions": "Cook pasta 2 minutes less than package directions. Drain.\nMake béchamel: melt butter, whisk in flour, cook 2 min, gradually add warm milk, simmer until thick.\nRemove from heat, stir in cheeses until smooth. Add mustard and paprika, season generously.\nCombine with pasta. Transfer to a baking dish.\nTop with breadcrumbs mixed with melted butter.\nBroil 3–4 minutes until top is golden and bubbling. Serve immediately.",
    },
    {
        "recipe_name": "BBQ Baby Back Ribs",
        "cuisine": "American",
        "category": "Main",
        "tags": "BBQ, weekend, summer",
        "prep_time": 20,
        "cook_time": 240,
        "servings": 4,
        "image_url": "https://images.unsplash.com/photo-1544025162-d76694265947?w=800",
        "ingredients": [
            {"name": "Baby back ribs", "quantity": "2", "unit": "racks"},
            {"name": "Brown sugar", "quantity": "3", "unit": "tbsp"},
            {"name": "Smoked paprika", "quantity": "2", "unit": "tbsp"},
            {"name": "Garlic powder", "quantity": "1", "unit": "tbsp"},
            {"name": "Onion powder", "quantity": "1", "unit": "tbsp"},
            {"name": "Cayenne pepper", "quantity": "1", "unit": "tsp"},
            {"name": "BBQ sauce", "quantity": "1", "unit": "cup"},
            {"name": "Apple cider vinegar", "quantity": "2", "unit": "tbsp"},
        ],
        "instructions": "Remove membrane from the back of ribs.\nMix brown sugar, paprika, garlic powder, onion powder, cayenne, salt, and pepper for the rub.\nCoat ribs generously with rub. Wrap in foil and refrigerate overnight if possible.\nPreheat oven to 150°C. Place foil-wrapped ribs on a baking sheet. Bake 3 hours.\nMix BBQ sauce with apple cider vinegar.\nUnwrap ribs, brush with sauce. Broil or grill 5 minutes per side until caramelized.\nRest 10 minutes, slice between bones.",
    },
    {
        "recipe_name": "Buttermilk Pancakes",
        "cuisine": "American",
        "category": "Breakfast",
        "tags": "breakfast, weekend, vegetarian",
        "prep_time": 10,
        "cook_time": 20,
        "servings": 4,
        "image_url": "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800",
        "ingredients": [
            {"name": "All-purpose flour", "quantity": "2", "unit": "cups"},
            {"name": "Buttermilk", "quantity": "2", "unit": "cups"},
            {"name": "Eggs", "quantity": "2", "unit": ""},
            {"name": "Butter (melted)", "quantity": "3", "unit": "tbsp"},
            {"name": "Sugar", "quantity": "2", "unit": "tbsp"},
            {"name": "Baking powder", "quantity": "2", "unit": "tsp"},
            {"name": "Baking soda", "quantity": "1/2", "unit": "tsp"},
            {"name": "Salt", "quantity": "1/2", "unit": "tsp"},
            {"name": "Maple syrup", "quantity": "1/4", "unit": "cup"},
        ],
        "instructions": "Whisk together flour, sugar, baking powder, baking soda, and salt.\nIn another bowl, whisk buttermilk, eggs, and melted butter.\nPour wet into dry, stir until just combined — lumps are fine, do not overmix.\nLet batter rest 5 minutes.\nHeat a skillet or griddle over medium heat, lightly grease.\nPour 1/3 cup batter per pancake. Cook until bubbles form and edges look set, 2–3 minutes. Flip, cook 1–2 more minutes.\nServe immediately with maple syrup and butter.",
    },
    {
        "recipe_name": "Chocolate Chip Cookies",
        "cuisine": "American",
        "category": "Dessert",
        "tags": "dessert, baking, classic",
        "prep_time": 15,
        "cook_time": 12,
        "servings": 24,
        "image_url": "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=800",
        "ingredients": [
            {"name": "All-purpose flour", "quantity": "2 1/4", "unit": "cups"},
            {"name": "Butter (softened)", "quantity": "230", "unit": "g"},
            {"name": "Brown sugar", "quantity": "3/4", "unit": "cup"},
            {"name": "Granulated sugar", "quantity": "3/4", "unit": "cup"},
            {"name": "Eggs", "quantity": "2", "unit": ""},
            {"name": "Vanilla extract", "quantity": "2", "unit": "tsp"},
            {"name": "Baking soda", "quantity": "1", "unit": "tsp"},
            {"name": "Salt", "quantity": "1", "unit": "tsp"},
            {"name": "Chocolate chips", "quantity": "350", "unit": "g"},
        ],
        "instructions": "Preheat oven to 190°C. Line baking sheets with parchment paper.\nBeat butter and both sugars together until light and fluffy, 3–4 minutes.\nAdd eggs one at a time, then vanilla. Beat well.\nWhisk flour, baking soda, and salt together. Gradually mix into butter mixture.\nFold in chocolate chips.\nRefrigerate dough 30 minutes for thicker cookies (optional but recommended).\nScoop rounded tablespoons onto prepared sheets, 5cm apart.\nBake 10–12 minutes until edges are set but centers look underdone.\nCool on pan 5 minutes before transferring.",
    },
    # ── French ────────────────────────────────────────────────────────────────
    {
        "recipe_name": "French Onion Soup",
        "cuisine": "French",
        "category": "Soup",
        "tags": "soup, comfort food, vegetarian",
        "prep_time": 15,
        "cook_time": 75,
        "servings": 4,
        "image_url": "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800",
        "ingredients": [
            {"name": "Yellow onions", "quantity": "1.5", "unit": "kg"},
            {"name": "Butter", "quantity": "60", "unit": "g"},
            {"name": "Olive oil", "quantity": "2", "unit": "tbsp"},
            {"name": "Beef or vegetable broth", "quantity": "1.5", "unit": "L"},
            {"name": "Dry white wine", "quantity": "150", "unit": "ml"},
            {"name": "Fresh thyme", "quantity": "4", "unit": "sprigs"},
            {"name": "Bay leaves", "quantity": "2", "unit": ""},
            {"name": "Baguette", "quantity": "8", "unit": "slices"},
            {"name": "Gruyère", "quantity": "200", "unit": "g"},
        ],
        "instructions": "Thinly slice all onions. Melt butter and olive oil in a heavy pot over medium heat.\nAdd onions and a pinch of salt. Cook, stirring occasionally, 45–60 minutes until deeply caramelized.\nDeglaze with wine, scraping up any browned bits. Cook until wine evaporates.\nAdd broth, thyme, and bay leaves. Simmer 20 minutes. Season well.\nToast baguette slices under broiler until golden.\nLadle soup into oven-safe bowls. Float 2 baguette slices on top, cover generously with grated Gruyère.\nBroil until cheese is bubbly and golden, 3–4 minutes.",
    },
    {
        "recipe_name": "Crème Brûlée",
        "cuisine": "French",
        "category": "Dessert",
        "tags": "dessert, elegant, baking",
        "prep_time": 20,
        "cook_time": 45,
        "servings": 6,
        "image_url": "https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc?w=800",
        "ingredients": [
            {"name": "Heavy cream", "quantity": "500", "unit": "ml"},
            {"name": "Egg yolks", "quantity": "5", "unit": ""},
            {"name": "Granulated sugar", "quantity": "100", "unit": "g"},
            {"name": "Vanilla bean", "quantity": "1", "unit": ""},
            {"name": "Fine sugar (for topping)", "quantity": "6", "unit": "tsp"},
        ],
        "instructions": "Preheat oven to 150°C.\nSplit vanilla bean, scrape seeds into cream. Heat cream until just simmering, then steep 10 minutes.\nWhisk yolks with sugar until pale and slightly thickened.\nSlowly pour warm cream into yolks while whisking constantly.\nStrain through a fine sieve. Skim off foam.\nPour into 6 ramekins set in a baking dish. Fill dish with hot water halfway up ramekins.\nBake 35–40 minutes until just set with a slight jiggle in the center.\nCool, then refrigerate at least 4 hours.\nBefore serving, sprinkle 1 tsp fine sugar on each and torch until caramelized.",
    },
    # ── Indian ────────────────────────────────────────────────────────────────
    {
        "recipe_name": "Dal Makhani",
        "cuisine": "Indian",
        "category": "Lentils",
        "tags": "vegetarian, comfort food, healthy",
        "prep_time": 15,
        "cook_time": 60,
        "servings": 6,
        "image_url": "https://images.unsplash.com/photo-1546833998-877b37c2e576?w=800",
        "ingredients": [
            {"name": "Black lentils (whole urad dal)", "quantity": "300", "unit": "g"},
            {"name": "Kidney beans (cooked)", "quantity": "200", "unit": "g"},
            {"name": "Butter", "quantity": "60", "unit": "g"},
            {"name": "Onion", "quantity": "1", "unit": "large"},
            {"name": "Garlic", "quantity": "6", "unit": "cloves"},
            {"name": "Ginger", "quantity": "2", "unit": "inch"},
            {"name": "Crushed tomatoes", "quantity": "400", "unit": "g"},
            {"name": "Heavy cream", "quantity": "100", "unit": "ml"},
            {"name": "Garam masala", "quantity": "1", "unit": "tsp"},
            {"name": "Cumin", "quantity": "1", "unit": "tsp"},
            {"name": "Coriander", "quantity": "1", "unit": "tsp"},
        ],
        "instructions": "Soak lentils overnight. Drain, simmer in fresh water 45–60 minutes until completely soft.\nMelt butter in a heavy pan. Sauté onion until golden, 10 minutes.\nAdd garlic and ginger paste, cook 2 minutes.\nAdd cumin, coriander, and garam masala. Cook 1 minute.\nAdd crushed tomatoes, cook down 15 minutes.\nStir in cooked lentils and kidney beans. Simmer 20 minutes, mashing some lentils against the side.\nAdd cream, season generously. Simmer 10 more minutes.\nFinish with a knob of butter. Serve with naan or basmati rice.",
    },
    {
        "recipe_name": "Palak Paneer",
        "cuisine": "Indian",
        "category": "Main",
        "tags": "vegetarian, healthy, curry",
        "prep_time": 20,
        "cook_time": 30,
        "servings": 4,
        "image_url": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=800",
        "ingredients": [
            {"name": "Fresh spinach", "quantity": "500", "unit": "g"},
            {"name": "Paneer", "quantity": "300", "unit": "g"},
            {"name": "Onion", "quantity": "1", "unit": ""},
            {"name": "Tomato", "quantity": "2", "unit": ""},
            {"name": "Garlic", "quantity": "4", "unit": "cloves"},
            {"name": "Ginger", "quantity": "1", "unit": "inch"},
            {"name": "Heavy cream", "quantity": "60", "unit": "ml"},
            {"name": "Garam masala", "quantity": "1", "unit": "tsp"},
            {"name": "Cumin seeds", "quantity": "1", "unit": "tsp"},
            {"name": "Green chili", "quantity": "1", "unit": ""},
            {"name": "Butter or ghee", "quantity": "2", "unit": "tbsp"},
        ],
        "instructions": "Blanch spinach 1 minute, drain and blend with green chili until smooth.\nFry paneer cubes in butter until golden. Set aside.\nIn the same pan, add cumin seeds until they splutter.\nAdd onion and cook until golden. Add garlic and ginger, cook 2 minutes.\nAdd tomatoes and cook until soft, 8 minutes. Add garam masala.\nStir in spinach purée, simmer 5 minutes.\nAdd paneer and cream, stir gently to combine.\nSimmer 3 minutes. Serve with rice or naan.",
    },
    # ── Mediterranean / Middle Eastern ────────────────────────────────────────
    {
        "recipe_name": "Hummus",
        "cuisine": "Mediterranean",
        "category": "Dip",
        "tags": "vegan, healthy, dip, quick",
        "prep_time": 15,
        "cook_time": 0,
        "servings": 6,
        "image_url": "https://images.unsplash.com/photo-1637951440219-85e64e7dc06c?w=800",
        "ingredients": [
            {"name": "Chickpeas (cooked or canned)", "quantity": "400", "unit": "g"},
            {"name": "Tahini", "quantity": "60", "unit": "ml"},
            {"name": "Lemon juice", "quantity": "3", "unit": "tbsp"},
            {"name": "Garlic", "quantity": "1", "unit": "clove"},
            {"name": "Ice water", "quantity": "3", "unit": "tbsp"},
            {"name": "Cumin", "quantity": "1/2", "unit": "tsp"},
            {"name": "Olive oil", "quantity": "2", "unit": "tbsp"},
            {"name": "Paprika", "quantity": "1/2", "unit": "tsp"},
        ],
        "instructions": "If using canned chickpeas, rub them between towels to remove skins for the creamiest result.\nBlend garlic and lemon juice first, let sit 5 minutes (takes edge off raw garlic).\nAdd tahini and blend 1 minute until creamy.\nAdd chickpeas, cumin, and salt. Blend 1 minute.\nWith machine running, drizzle in ice water until you reach your desired texture. Blend 3–4 minutes for silky smooth.\nServe in a bowl, drizzle with olive oil, sprinkle paprika, garnish with whole chickpeas and herbs.",
    },
    {
        "recipe_name": "Tabbouleh",
        "cuisine": "Mediterranean",
        "category": "Salad",
        "tags": "salad, healthy, vegan, quick",
        "prep_time": 20,
        "cook_time": 0,
        "servings": 4,
        "image_url": "https://images.unsplash.com/photo-1505576399279-565b52d4ac71?w=800",
        "ingredients": [
            {"name": "Fine bulgur wheat", "quantity": "60", "unit": "g"},
            {"name": "Flat-leaf parsley", "quantity": "3", "unit": "bunches"},
            {"name": "Fresh mint", "quantity": "1", "unit": "bunch"},
            {"name": "Roma tomatoes", "quantity": "3", "unit": ""},
            {"name": "Green onions", "quantity": "4", "unit": ""},
            {"name": "Lemon juice", "quantity": "60", "unit": "ml"},
            {"name": "Olive oil", "quantity": "60", "unit": "ml"},
        ],
        "instructions": "Pour boiling water over bulgur just to cover. Let sit 10 minutes, fluff with a fork, cool completely.\nFinely chop parsley and mint leaves (no stems). This is the bulk of the salad.\nDice tomatoes small, slice green onions thinly.\nCombine all ingredients, drizzle with lemon juice and olive oil.\nToss well and season generously with salt and pepper.\nTabbouleh improves after 30 minutes as flavors meld. Serve at room temperature.",
    },
    # ── Soups & Stews ─────────────────────────────────────────────────────────
    {
        "recipe_name": "Tom Kha Gai",
        "cuisine": "Thai",
        "category": "Soup",
        "tags": "soup, coconut, comfort food",
        "prep_time": 15,
        "cook_time": 20,
        "servings": 4,
        "image_url": "https://images.unsplash.com/photo-1548943487-a2e4e43b4853?w=800",
        "ingredients": [
            {"name": "Chicken breast", "quantity": "400", "unit": "g"},
            {"name": "Coconut milk", "quantity": "800", "unit": "ml"},
            {"name": "Chicken broth", "quantity": "400", "unit": "ml"},
            {"name": "Galangal", "quantity": "5", "unit": "slices"},
            {"name": "Lemongrass", "quantity": "2", "unit": "stalks"},
            {"name": "Kaffir lime leaves", "quantity": "5", "unit": ""},
            {"name": "Mushrooms", "quantity": "200", "unit": "g"},
            {"name": "Fish sauce", "quantity": "3", "unit": "tbsp"},
            {"name": "Lime juice", "quantity": "3", "unit": "tbsp"},
            {"name": "Palm sugar", "quantity": "1", "unit": "tsp"},
            {"name": "Thai chiles", "quantity": "2", "unit": ""},
            {"name": "Cilantro", "quantity": "1/4", "unit": "cup"},
        ],
        "instructions": "Bruise lemongrass and slice galangal. Tear lime leaves.\nSimmer coconut milk and broth together with galangal, lemongrass, and lime leaves for 5 minutes.\nAdd sliced chicken and mushrooms. Cook 8–10 minutes until chicken is cooked through.\nSeason with fish sauce, lime juice, and palm sugar.\nTaste: it should be salty, sour, and slightly sweet with a creamy coconut base.\nLadle into bowls, garnish with cilantro and chiles. Remove lemongrass before eating.",
    },
    {
        "recipe_name": "Beef Stew",
        "cuisine": "American",
        "category": "Stew",
        "tags": "comfort food, weekend, hearty",
        "prep_time": 20,
        "cook_time": 120,
        "servings": 6,
        "image_url": "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800",
        "ingredients": [
            {"name": "Beef chuck (cubed)", "quantity": "1", "unit": "kg"},
            {"name": "Yukon gold potatoes", "quantity": "500", "unit": "g"},
            {"name": "Carrots", "quantity": "3", "unit": ""},
            {"name": "Celery", "quantity": "3", "unit": "stalks"},
            {"name": "Onion", "quantity": "1", "unit": ""},
            {"name": "Garlic", "quantity": "4", "unit": "cloves"},
            {"name": "Tomato paste", "quantity": "2", "unit": "tbsp"},
            {"name": "Red wine", "quantity": "250", "unit": "ml"},
            {"name": "Beef broth", "quantity": "750", "unit": "ml"},
            {"name": "Fresh thyme", "quantity": "4", "unit": "sprigs"},
            {"name": "Bay leaves", "quantity": "2", "unit": ""},
            {"name": "Flour", "quantity": "2", "unit": "tbsp"},
        ],
        "instructions": "Season beef generously with salt and pepper. Dust with flour.\nSear beef in batches in a hot Dutch oven until deeply browned on all sides. Set aside.\nSauté onion, carrots, and celery until soft. Add garlic and tomato paste, cook 2 minutes.\nDeglaze with red wine, scraping up browned bits. Reduce by half.\nReturn beef, add broth, thyme, and bay leaves. Bring to a simmer.\nCover and cook low for 1.5 hours.\nAdd potatoes, cook 30 more minutes until potatoes and beef are both tender.\nDiscard thyme and bay leaves. Adjust seasoning.",
    },
]


async def run():
    client = AsyncIOMotorClient(URI)
    db = client[DB]

    # Find master user
    master = await db.users.find_one({"email": "master@mise.com"})
    if not master:
        print("ERROR: master@mise.com not found in DB")
        client.close()
        return

    uid = str(master["_id"])
    print(f"Found master@mise.com  id={uid}")

    now = datetime.now(timezone.utc)
    docs = []
    for r in RECIPES:
        docs.append({
            **r,
            "user_id": uid,
            "is_public": True,
            "like_count": 0,
            "is_modified": False,
            "original_recipe_id": None,
            "original_author_name": None,
            "author_name": master.get("name", "master"),
            "created_at": now,
        })

    result = await db.recipes.insert_many(docs)
    print(f"Inserted {len(result.inserted_ids)} recipes")
    client.close()


asyncio.run(run())
